name: AutoCheckin
on:
  push:
    branches:
      - main
  schedule: # Github 为 UTC 时间，需要把 北京时间 4:30 转换为 UTC 时间 即 20:30
    - cron: '30 20 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install httpx

      - name: Run Python script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
          DOMAIN: ${{ vars.DOMAIN }}
        run: python checkin.py
